### ISSUE TITLE
Add Occidental - Esperanto dictionarium

### ISSUE THREAD

**Issue by Dhghomon** [occidental-lang/dictionaries#3]
Can be found here:

http://interlingue.narod.ru/VocInEs/VocInEs.zip

**Comment by trosel** [comment]
@Dhghomon would this be more useful if I reversed the order? So it's esperanto->occ?

**Comment by Dhghomon** [comment]
Oh right, silly me. The order should be Esperanto -> Occ.

**Comment by trosel** [comment]
I'll change the order when I upload

**Comment by trosel** [comment]
Just a little note from the document:

> corectet 05.09.2005
digitalisat de Sergey Belitzky

**Comment by trosel** [comment]
done: https://github.com/occidental-lang/dictionaries/commit/c474a5024ecf4634c6f28b89cbd8ee05f3311708
